SDK=alphadata
PLATFORM_VENDOR=alphadata
PLATFORM?=admxrc6t1
PLATFORM_TARGET?=xc6vlx240t-noddr
DEVICE_VENDOR=xilinx
DEVICE_FAMILY=virtex6
DEVICE=xc6vlx240t
PACKAGE=ff1159
SPEEDGRADE=m1

DESIGNER?=pa
DESIGNER_VERSION?=14.4