-- This file was automatically generated by ROCCC -- version 0.7.4.0, released on Monday, January 17, 2011, DO NOT EDIT
library IEEE ;
use IEEE.STD_LOGIC_1164.all ;
use IEEE.STD_LOGIC_ARITH.ALL;
use IEEE.STD_LOGIC_UNSIGNED.all ;
use work.HelperFunctions.all;
use work.HelperFunctions_Unsigned.all;
use work.HelperFunctions_Signed.all;

entity adder is
port (
	clk : in STD_LOGIC;
	rst : in STD_LOGIC;
	inputReady : in STD_LOGIC;
	outputReady : out STD_LOGIC;
	done : out STD_LOGIC;
	stall : in STD_LOGIC;
	a_in : in STD_LOGIC_VECTOR(31 downto 0);
	b_in : in STD_LOGIC_VECTOR(31 downto 0);
	r_out_out : out STD_LOGIC_VECTOR(31 downto 0)
	);
end entity;

architecture Synthesized of adder is 
signal a719 : STD_LOGIC_VECTOR(31 downto 0) ;
signal r_out1428 : STD_LOGIC_VECTOR(31 downto 0) ;
signal b1024 : STD_LOGIC_VECTOR(31 downto 0) ;
signal stall_previous : STD_LOGIC ;
signal activeStates : STD_LOGIC ;
signal adder_done : STD_LOGIC ;
begin
done <= adder_done;
r_out1428 <= ROCCCADD(a719, b1024, 32);
process(clk, rst)
begin
  if (rst = '1') then
    stall_previous <= '0';
    activeStates <= '0';
    a719 <= "00000000000000000000000000000000";
    b1024 <= "00000000000000000000000000000000";
    outputReady <= '0';
    adder_done <= '0';
    r_out_out <= "00000000000000000000000000000000";
  elsif( clk'event and clk = '1' ) then
    outputReady <= '0';
    stall_previous <= stall;
    if( ((stall /= '1') or (stall_previous = '0')) ) then
      activeStates <= inputReady;
    end if;
    if( ((inputReady = '1') and ((stall /= '1') or (stall_previous = '0'))) ) then
      a719 <= a_in;
      b1024 <= b_in;
    end if;
    if( ((activeStates = '1') and ((stall /= '1') or (stall_previous = '0'))) ) then
    end if;
    if( ((activeStates = '1') and ((stall /= '1') or (stall_previous = '0'))) ) then
      outputReady <= '1';
      adder_done <= '1';
      r_out_out <= r_out1428;
    end if;
  end if;
end process;
end Synthesized;
